 name: Greetings

 on:
   issues:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for concern , This is your first issue in our repository'
        pr-message: 'Thanks for concern , This is your first pull request in our repository'
 
 # or use below Steps represent a sequence of tasks that will be executed as part of the job
   # steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     # - uses: actions/checkout@v2

     # Runs a single command using the runners shell
     # - name: Run a one-line script
     #   run: echo Hello, world!

     # Runs a set of commands using the runners shell
     # - name: Run a multi-line script
     #   run: |
     #     echo Add other actions to build,
     #     echo test, and deploy your project.
 
